modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
logoFile="icon.png"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[modproperties."${mod_id}"]
catalogueImageIcon="icon.png"
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "curios"
mandatory = true
versionRange = "${curios_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "mekanism"
mandatory = true
versionRange = "${mekanism_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange = "${create_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "tconstruct"
mandatory = true
versionRange = "${tconstruct_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "immersiveengineering"
mandatory = true
versionRange = "${immersiveengineering_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "patchouli"
mandatory = true
versionRange = "[1.20.1-84.1-FORGE,)"
[[dependencies."${mod_id}"]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.1,)"
[[dependencies."${mod_id}"]]
modId = "alexscaves"
mandatory = true
versionRange = "[2.0.2,)"
[[dependencies."${mod_id}"]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.5-build.16,)"
[[dependencies."${mod_id}"]]
modId = "rhino"
mandatory = true
versionRange = "[2001.2.3-build.10,)"
[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = true
versionRange = "${jei_version_range}"